title = 'My New Hugo Site'
theme = "universal"

baseURL = "https://Whitsand-Bay-Surf-Lifesaving-Club.github.io/www"
publishDir = "docs"

[params]
    disabled_logo = false
    logo_text = "Whitsand Bay Surf Lifesaving"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1
