backend:
  name: github
  repo: Whitsand-Bay-Surf-Lifesaving-Club/whitsand-bay-surf-lifesaving-club.github.io
  branch: main
  site_domain: https://www.whitsandsurf.com
  base_url: https://www.whitsandsurf.com

  auth_scope: repo
  app_id: "${OAUTH_CLIENT_ID}"
  app_secret: "${OAUTH_CLIENT_SECRET}"

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: https://www.whitsandsurf.com

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

